#!/usr/bin/env sh

[ -t 0 ] && [ -t 1 ] || exit 0

MOTD_TEMPLATE_FILE="${MOTD_TEMPLATE_FILE:-/usr/share/lyftos/motd/welcome.txt}"
. "${MOTD_ENV_SCRIPT:-/usr/share/lyftos/motd/env.sh}"

if command -v tput >/dev/null 2>&1 && [ -t 1 ]; then
  cols=$(tput cols 2>/dev/null)
  envsubst < "${MOTD_TEMPLATE_FILE}" | glow -w $cols -
else
  envsubst < "${MOTD_TEMPLATE_FILE}" | glow -
fi

